CREATE TABLE Banco (
    IdBanco NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE Usuario (
    IdUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    ApellidoPaterno VARCHAR(50) NOT NULL,
    ApellidoMaterno VARCHAR(50) NOT NULL,
    Curp VARCHAR(18) NOT NULL UNIQUE,
    FechaNacimiento DATE NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(200) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    FechaCreacion DATE DEFAULT SYSDATE
)

CREATE TABLE Cuenta(
    IdCuenta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdUsuario NUMBER,
    IdBanco NUMBER,
    NumeroCuenta VARCHAR(20) UNIQUE,
    Saldo NUMBER (12,2),
    
    FOREIGN KEY(IdUsuario) REFERENCES Usuario(IdUsuario),
    FOREIGN KEY(IdBanco) REFERENCES Banco(IdBanco)
) 

CREATE TABLE Tarjeta(
    IdTarjeta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdCuenta NUMBER,
    NumeroTarjeta VARCHAR(20) UNIQUE,
    Nip NUMBER(4),
    VerificacionNip NUMBER(1) DEFAULT 0,
    
    FOREIGN KEY(IdCuenta) REFERENCES Cuenta(IdCuenta)
)


INSERT INTO Banco(Nombre) VALUES('BBVA')
INSERT INTO Banco(Nombre) VALUES('Coppel')
INSERT INTO Banco(Nombre) VALUES('Santander')
INSERT INTO Banco(Nombre) VALUES('Banamex')


ALTER TABLE Usuario ADD FechaNacimiento DATE;

select * from cuenta

CREATE OR REPLACE PROCEDURE BancoGetAllSP(
    pCursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN pCursor FOR SELECT IdBanco, Nombre FROM Banco ORDER BY IdBanco;
END;
/

CREATE OR REPLACE PROCEDURE RetiroSP(
    pIdTarjeta IN NUMBER,
    pMonto IN NUMBER
)
AS
    vIdCuenta NUMBER;
    vSaldo NUMBER(12,2);
BEGIN
    SELECT IdCuenta INTO vIdCuenta FROM Tarjeta WHERE IdTarjeta = pIdTarjeta;
    
    SELECT Saldo INTO vSaldo FROM Cuenta WHERE IdCuenta = vIdCuenta;
    
    IF vSaldo < pMonto THEN 
    
        RAISE_APPLICATION_ERROR(
            -20001,
            'Saldo insuficiente'
            );
    END IF;
    
    UPDATE Cuenta SET Saldo = Saldo - pMonto WHERE IdCuenta = vIdCuenta;
    
    COMMIT;
    
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
            
END;
/



CREATE OR REPLACE PROCEDURE TarjetaLoginSP(
    pCursor OUT SYS_REFCURSOR,
    pNumeroTarjeta IN VARCHAR,
    pNip IN NUMBER
)
AS
BEGIN
    OPEN pCursor FOR
        SELECT tarjeta.IdTarjeta, tarjeta.NumeroTarjeta, tarjeta.Nip, cuenta.IdCuenta, cuenta.Saldo, banco.Nombre 
        FROM Tarjeta tarjeta INNER JOIN Cuenta cuenta ON tarjeta.IdCuenta = cuenta.IdCuenta 
        INNER JOIN Banco banco ON cuenta.IdBanco = banco.IdBanco WHERE tarjeta.numeroTarjeta = pNumeroTarjeta 
        AND tarjeta.Nip = pNip;
END;
/










CREATE OR REPLACE PROCEDURE RegistrarUsuarioSP(

    P_NOMBRE IN VARCHAR2,
    P_APELLIDOPATERNO IN VARCHAR2,
    P_APELLIDOMATERNO IN VARCHAR2,
    P_Curp IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_PASSWORD IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_FechaNacimiento IN DATE,
    P_IDBANCO IN NUMBER,

    P_IDUSUARIO OUT NUMBER

)
AS

    V_IDUSUARIO NUMBER;
    V_IDCUENTA NUMBER;
    V_NUMEROCUENTA VARCHAR2(20);
    V_SALDO NUMBER(12,2);
    V_IDTARJETA NUMBER;
    V_NUMEROTARJETA VARCHAR2(20);
    V_NIP NUMBER(4);

BEGIN

    ------------------------------------------------
    -- INSERTAR USUARIO
    ------------------------------------------------

    INSERT INTO Usuario(

        Nombre,
        ApellidoPaterno,
        ApellidoMaterno,
        Curp,
        Email,
        Password,
        Telefono,
        FechaNacimiento

    )
    VALUES(

        P_NOMBRE,
        P_APELLIDOPATERNO,
        P_APELLIDOMATERNO,
        P_CURP,
        P_EMAIL,
        P_PASSWORD,
        P_TELEFONO,
        P_FechaNacimiento

    )
    RETURNING IdUsuario
    INTO V_IDUSUARIO;

    ------------------------------------------------
    -- GENERAR NUMERO DE CUENTA
    ------------------------------------------------

    V_NUMEROCUENTA :=
        TO_CHAR(
            TRUNC(
                DBMS_RANDOM.VALUE(
                    1000000000,
                    9999999999
                )
            )
        );

    ------------------------------------------------
    -- SALDO ALEATORIO
    ------------------------------------------------

    V_SALDO :=
        ROUND(
            DBMS_RANDOM.VALUE(
                10000,
                50000
            ),
            2
        );

    ------------------------------------------------
    -- INSERTAR CUENTA
    ------------------------------------------------

    INSERT INTO Cuenta(

        IdUsuario,
        IdBanco,
        NumeroCuenta,
        Saldo

    )
    VALUES(

        V_IDUSUARIO,
        P_IDBANCO,
        V_NUMEROCUENTA,
        V_SALDO

    )
    RETURNING IdCuenta
    INTO V_IDCUENTA;

    ------------------------------------------------
    -- GENERAR NUMERO TARJETA
    ------------------------------------------------

    V_NUMEROTARJETA :=
        TO_CHAR(
            TRUNC(
                DBMS_RANDOM.VALUE(
                    4000000000000000,
                    4999999999999999
                )
            )
        );

    ------------------------------------------------
    -- GENERAR NIP
    ------------------------------------------------

    V_NIP :=
        TRUNC(
            DBMS_RANDOM.VALUE(
                1000,
                9999
            )
        );

    ------------------------------------------------
    -- INSERTAR TARJETA
    ------------------------------------------------

    INSERT INTO Tarjeta(

        IdCuenta,
        NumeroTarjeta,
        Nip

    )
    VALUES(

        V_IDCUENTA,
        V_NUMEROTARJETA,
        V_NIP

    )
    RETURNING IdTarjeta
    INTO V_IDTARJETA;

    ------------------------------------------------
    -- DEVOLVER ID USUARIO
    ------------------------------------------------

    P_IDUSUARIO := V_IDUSUARIO;

    COMMIT;

EXCEPTION

    WHEN OTHERS THEN

        ROLLBACK;
        RAISE;

END;
/
















DECLARE

    V_IDUSUARIO NUMBER;

BEGIN

    RegistrarUsuarioSP(

        'Alfonso',
        'Moreno',
        'Juarez',
        'alfonso@gmail.com',
        '12345',
        '7221234567',
        TO_DATE('2002-05-10','YYYY-MM-DD'),
        1,

        V_IDUSUARIO

    );

    DBMS_OUTPUT.PUT_LINE(
        'ID USUARIO: ' || V_IDUSUARIO
    );

END;
/






